
package ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ILegalInq", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ILegalInq {


    /**
     * 
     * @param password
     * @param nationalId
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3.LegalInqRes
     */
    @WebMethod(operationName = "SubmitNationalIdInq", action = "http://tempuri.org/ILegalInq/SubmitNationalIdInq")
    @WebResult(name = "SubmitNationalIdInqResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SubmitNationalIdInq", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3.SubmitNationalIdInq")
    @ResponseWrapper(localName = "SubmitNationalIdInqResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3.SubmitNationalIdInqResponse")
    public LegalInqRes submitNationalIdInq(
        @WebParam(name = "nationalId", targetNamespace = "http://tempuri.org/")
        String nationalId,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param fullName
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3.LegalInqRes
     */
    @WebMethod(operationName = "SubmitFullNameInq", action = "http://tempuri.org/ILegalInq/SubmitFullNameInq")
    @WebResult(name = "SubmitFullNameInqResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SubmitFullNameInq", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3.SubmitFullNameInq")
    @ResponseWrapper(localName = "SubmitFullNameInqResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3.SubmitFullNameInqResponse")
    public LegalInqRes submitFullNameInq(
        @WebParam(name = "fullName", targetNamespace = "http://tempuri.org/")
        String fullName,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

    /**
     * 
     * @param password
     * @param archiveName
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3.LegalInqRes
     */
    @WebMethod(operationName = "SubmitFullArchiveNameInq", action = "http://tempuri.org/ILegalInq/SubmitFullArchiveNameInq")
    @WebResult(name = "SubmitFullArchiveNameInqResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "SubmitFullArchiveNameInq", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3.SubmitFullArchiveNameInq")
    @ResponseWrapper(localName = "SubmitFullArchiveNameInqResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.ashkhasehoghooghi_v3.SubmitFullArchiveNameInqResponse")
    public LegalInqRes submitFullArchiveNameInq(
        @WebParam(name = "archiveName", targetNamespace = "http://tempuri.org/")
        String archiveName,
        @WebParam(name = "username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "password", targetNamespace = "http://tempuri.org/")
        String password);

}
