package ir.parsianinsurance.he.infrastructure.security;

/**
 * Created by Mohammad on 8/6/2017.
 */
public enum Permission {

    MOSHAHEBE_BIMENAME,
    MOSHAHEDE_ELHAGHIYE,
    MOSHAHEDE_KHESARAT,
    MOSHAHEDE_DARKHAST,
    SODOOR_BIMENAME,
    SABT_PISHNAHAD,
    EDIT_PISHNAHAD,
    SODOOR_KHESARAT,
    SABT_ELHAGHIYE_TAGHIR,
    SABT_FASKH,
    SABT_EBTAL,
    MOSHAHEDE_AGENCY_BIMENAMES,
    MOSHAHEDE_GOZARESH,
    CHAP_HAGHEBIME,
    CHAP_BIMENAME,
    CHAP_ELHAGHIYE,
    CHAP_KHESARAT,
    NAMAYESHE_JOZIATE_BIMENAME,
    NAMAYESHE_JOZIATE_ELHAGHIYE,
    DARKHAST_MOJAVEZ_ROOYE_BIMENAME,
    NAMAYESHE_JOZIATE_KHESARAT,
    VIRAYESHE_KHESARAT,
    SABTE_HAVALE_KHESARAT
}
