package ir.parsianinsurance.he.interfaces.view.uiflow;

/**
 * Created by Mohammad on 6/28/2017.
 */
public enum StateName {

    SABT_PISHNAHAD,
    VIRAYESH_PISHNAHAD,
    LIST_BIMENAME,
    SODOOR_NEW_BIMENAME,
    SABT_NEW_PISHNAHAD_MOHASEBE,
    BIMENAME_SELECTED,
    LIST_ELHAGHIYE,
    ELHAGHIYE_SELECTED,
    NAMAYESH_BIMENAME,
    ELHAGHIYE_TAGHIRAT,
    FASKH,
    MOHASEBE_FASKH,
    NAMAYESH_ELHAGHIYE,
    ENSERAF_AZ_ELHAGHIYE,
    BAZGASHT_AZ_NAMAYESH,
    TAGHIR_BIMENAME,
    EBTAL,
    MOHASEBE_EBTAL,
    SODOOR_NEW_BIMENAME_MOHASEBE,
    TAGHIR_BIMENAME_MOHASEBE_HAGHEBIME,
    TAEEDE_ELHAGHIYE_TAGHIRAT,
    ESLAHE_SODOOR,
    TAEEDE_NAHAYI_ELHAGHIYE_TAGHIRAT,
    LIST_KHESARAT,
    KHESARAT,
    NAMAYESH_KHESARAT,
    VIRAYESH_KHESARAT,
    KHESARAT_SELECTED,
    SODOOR_NEW_HAVALE_KHESARAT,
    MODIRIATE_KARBARAN,
    MODIRIATE_GHARARDADHA,
    MODIRIATE_MASHAGHEL,
    MODIRIATE_NAMAYANDEGAN,
    BORDRO_BIMENAME,
    LIST_ARTIFACTDOC,
    BORDRO_ELHAGHIYE;

}
