
package ir.parsianinsurance.he.interfaces.webservice.client.sms;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ServiceHttpPost", targetNamespace = "http://www.SMS.parsianInsurance.ir/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ServiceHttpPost {


    /**
     * 
     * @param firstName
     * @param lastName
     * @param passwrd
     * @param policyID
     * @param appName
     * @param description
     * @param userName
     * @param cellPhone
     * @param smsText
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "InsertSMS")
    @WebResult(name = "string", targetNamespace = "http://www.SMS.parsianInsurance.ir/", partName = "Body")
    public String insertSMS(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserName")
        String userName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Passwrd")
        String passwrd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "FirstName")
        String firstName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LastName")
        String lastName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CellPhone")
        String cellPhone,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SMSText")
        String smsText,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Description")
        String description,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "PolicyID")
        String policyID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AppName")
        String appName);

    /**
     * 
     * @param firstName
     * @param lastName
     * @param passwrd
     * @param policyID
     * @param appName
     * @param description
     * @param userName
     * @param reservedField3
     * @param cellPhone
     * @param smsText
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Insert_Saiboon")
    @WebResult(name = "string", targetNamespace = "http://www.SMS.parsianInsurance.ir/", partName = "Body")
    public String insertSaiboon(
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "UserName")
        String userName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Passwrd")
        String passwrd,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "FirstName")
        String firstName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "LastName")
        String lastName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "CellPhone")
        String cellPhone,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "SMSText")
        String smsText,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "Description")
        String description,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "PolicyID")
        String policyID,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "AppName")
        String appName,
        @WebParam(name = "string", targetNamespace = "http://www.w3.org/2001/XMLSchema", partName = "ReservedField3")
        String reservedField3);

}
