
package ir.parsianinsurance.he.interfaces.webservice.client.sanam;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BitartsWebService", targetNamespace = "http://implementation.service.parsian.bitarts.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BitartsWebService {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "isSuspended", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.IsSuspended")
    @ResponseWrapper(localName = "isSuspendedResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.IsSuspendedResponse")
    public String isSuspended(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authenticate", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.Authenticate")
    @ResponseWrapper(localName = "authenticateResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.AuthenticateResponse")
    public String authenticate(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getDebtOfPolicy", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetDebtOfPolicy")
    @ResponseWrapper(localName = "getDebtOfPolicyResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetDebtOfPolicyResponse")
    public String getDebtOfPolicy(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "vaziatVosoolShenase", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.VaziatVosoolShenase")
    @ResponseWrapper(localName = "vaziatVosoolShenaseResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.VaziatVosoolShenaseResponse")
    public String vaziatVosoolShenase(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "estelamBashgah", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.EstelamBashgah")
    @ResponseWrapper(localName = "estelamBashgahResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.EstelamBashgahResponse")
    public String estelamBashgah(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "generateCustomerNumber", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GenerateCustomerNumber")
    @ResponseWrapper(localName = "generateCustomerNumberResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GenerateCustomerNumberResponse")
    public String generateCustomerNumber(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNamayandehAuthorized", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetNamayandehAuthorized")
    @ResponseWrapper(localName = "getNamayandehAuthorizedResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetNamayandehAuthorizedResponse")
    public String getNamayandehAuthorized(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNamayandehAuthorizedJSON", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetNamayandehAuthorizedJSON")
    @ResponseWrapper(localName = "getNamayandehAuthorizedJSONResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetNamayandehAuthorizedJSONResponse")
    public String getNamayandehAuthorizedJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        Long arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "deleteAghsat", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.DeleteAghsat")
    @ResponseWrapper(localName = "deleteAghsatResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.DeleteAghsatResponse")
    public String deleteAghsat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDebitJSON", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateDebitJSON")
    @ResponseWrapper(localName = "createDebitJSONResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateDebitJSONResponse")
    public String createDebitJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCreditJSON", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateCreditJSON")
    @ResponseWrapper(localName = "createCreditJSONResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateCreditJSONResponse")
    public String createCreditJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByAzMahaleTablighat", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByAzMahaleTablighat")
    @ResponseWrapper(localName = "payByAzMahaleTablighatResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByAzMahaleTablighatResponse")
    public String payByAzMahaleTablighat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getGhestForUSSDSanam", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetGhestForUSSDSanam")
    @ResponseWrapper(localName = "getGhestForUSSDSanamResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetGhestForUSSDSanamResponse")
    public String getGhestForUSSDSanam(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sanadRegisterJSON", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.SanadRegisterJSON")
    @ResponseWrapper(localName = "sanadRegisterJSONResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.SanadRegisterJSONResponse")
    public String sanadRegisterJSON(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByHesabFiMaBeyn", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByHesabFiMaBeyn")
    @ResponseWrapper(localName = "payByHesabFiMaBeynResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByHesabFiMaBeynResponse")
    public String payByHesabFiMaBeyn(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "updateShomareBimename", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.UpdateShomareBimename")
    @ResponseWrapper(localName = "updateShomareBimenameResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.UpdateShomareBimenameResponse")
    public boolean updateShomareBimename(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "amountOfShenasePardakhtSanam", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.AmountOfShenasePardakhtSanam")
    @ResponseWrapper(localName = "amountOfShenasePardakhtSanamResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.AmountOfShenasePardakhtSanamResponse")
    public String amountOfShenasePardakhtSanam(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "checkForTalighKhesarat", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CheckForTalighKhesarat")
    @ResponseWrapper(localName = "checkForTalighKhesaratResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CheckForTalighKhesaratResponse")
    public String checkForTalighKhesarat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createRecoveryForVehicle", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateRecoveryForVehicle")
    @ResponseWrapper(localName = "createRecoveryForVehicleResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateRecoveryForVehicleResponse")
    public String createRecoveryForVehicle(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getSoratVaziateMaliBimename", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetSoratVaziateMaliBimename")
    @ResponseWrapper(localName = "getSoratVaziateMaliBimenameResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetSoratVaziateMaliBimenameResponse")
    public String getSoratVaziateMaliBimename(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryRemainingWithIdentifier", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.QueryRemainingWithIdentifier")
    @ResponseWrapper(localName = "queryRemainingWithIdentifierResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.QueryRemainingWithIdentifierResponse")
    public Integer queryRemainingWithIdentifier(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryRemainingWithTraceCode", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.QueryRemainingWithTraceCode")
    @ResponseWrapper(localName = "queryRemainingWithTraceCodeResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.QueryRemainingWithTraceCodeResponse")
    public Integer queryRemainingWithTraceCode(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createHavaleKhesarat", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateHavaleKhesarat")
    @ResponseWrapper(localName = "createHavaleKhesaratResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateHavaleKhesaratResponse")
    public String createHavaleKhesarat(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByHesabFiMaBeynForElhaghie", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByHesabFiMaBeynForElhaghie")
    @ResponseWrapper(localName = "payByHesabFiMaBeynForElhaghieResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByHesabFiMaBeynForElhaghieResponse")
    public String payByHesabFiMaBeynForElhaghie(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "amountOfShenasePardakht", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.AmountOfShenasePardakht")
    @ResponseWrapper(localName = "amountOfShenasePardakhtResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.AmountOfShenasePardakhtResponse")
    public String amountOfShenasePardakht(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.Integer
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "queryRemainingWithShenase", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.QueryRemainingWithShenase")
    @ResponseWrapper(localName = "queryRemainingWithShenaseResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.QueryRemainingWithShenaseResponse")
    public Integer queryRemainingWithShenase(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByCash", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByCash")
    @ResponseWrapper(localName = "payByCashResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByCashResponse")
    public String payByCash(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByFish", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByFish")
    @ResponseWrapper(localName = "payByFishResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByFishResponse")
    public String payByFish(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        Integer arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg13
     * @param arg14
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByPOS", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByPOS")
    @ResponseWrapper(localName = "payByPOSResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByPOSResponse")
    public String payByPOS(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        Integer arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg17
     * @param arg2
     * @param arg18
     * @param arg5
     * @param arg4
     * @param arg13
     * @param arg14
     * @param arg1
     * @param arg15
     * @param arg0
     * @param arg16
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByCheck", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByCheck")
    @ResponseWrapper(localName = "payByCheckResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByCheckResponse")
    public String payByCheck(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        Integer arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15,
        @WebParam(name = "arg16", targetNamespace = "")
        String arg16,
        @WebParam(name = "arg17", targetNamespace = "")
        String arg17,
        @WebParam(name = "arg18", targetNamespace = "")
        String arg18);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "estelamBedehi", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.EstelamBedehi")
    @ResponseWrapper(localName = "estelamBedehiResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.EstelamBedehiResponse")
    public String estelamBedehi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByInternet", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByInternet")
    @ResponseWrapper(localName = "payByInternetResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByInternetResponse")
    public String payByInternet(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg13
     * @param arg14
     * @param arg1
     * @param arg15
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sanadRegister", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.SanadRegister")
    @ResponseWrapper(localName = "sanadRegisterResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.SanadRegisterResponse")
    public String sanadRegister(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        String arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12,
        @WebParam(name = "arg13", targetNamespace = "")
        String arg13,
        @WebParam(name = "arg14", targetNamespace = "")
        String arg14,
        @WebParam(name = "arg15", targetNamespace = "")
        String arg15);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCredit", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateCredit")
    @ResponseWrapper(localName = "createCreditResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateCreditResponse")
    public String createCredit(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        Integer arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        Long arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12);

    /**
     * 
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg11
     * @param arg12
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createDebit", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateDebit")
    @ResponseWrapper(localName = "createDebitResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.CreateDebitResponse")
    public String createDebit(
        @WebParam(name = "arg0", targetNamespace = "")
        Integer arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        Integer arg10,
        @WebParam(name = "arg11", targetNamespace = "")
        Long arg11,
        @WebParam(name = "arg12", targetNamespace = "")
        String arg12);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByACH", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByACH")
    @ResponseWrapper(localName = "payByACHResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByACHResponse")
    public String payByACH(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        Integer arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRemainingCrediteForQarardadAqsati", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetRemainingCrediteForQarardadAqsati")
    @ResponseWrapper(localName = "getRemainingCrediteForQarardadAqsatiResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.GetRemainingCrediteForQarardadAqsatiResponse")
    public String getRemainingCrediteForQarardadAqsati(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg10
     * @param arg7
     * @param arg6
     * @param arg9
     * @param arg8
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "payByAzMahaleTablighatForElhaghie", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByAzMahaleTablighatForElhaghie")
    @ResponseWrapper(localName = "payByAzMahaleTablighatForElhaghieResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.PayByAzMahaleTablighatForElhaghieResponse")
    public String payByAzMahaleTablighatForElhaghie(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        Integer arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        String arg8,
        @WebParam(name = "arg9", targetNamespace = "")
        String arg9,
        @WebParam(name = "arg10", targetNamespace = "")
        String arg10);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "estelamVaziateBedehiVaEtebar", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.EstelamVaziateBedehiVaEtebar")
    @ResponseWrapper(localName = "estelamVaziateBedehiVaEtebarResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.EstelamVaziateBedehiVaEtebarResponse")
    public String estelamVaziateBedehiVaEtebar(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "feedbackCredebit", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.FeedbackCredebit")
    @ResponseWrapper(localName = "feedbackCredebitResponse", targetNamespace = "http://implementation.service.parsian.bitarts.com/", className = "ir.parsianinsurance.he.interfaces.webservice.client.sanam.FeedbackCredebitResponse")
    public String feedbackCredebit(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
