
package ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "IWbsPlcyV4", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface IWbsPlcyV4 {


    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4AgncRes
     */
    @WebMethod(operationName = "CiiRegAgency", action = "http://tempuri.org/IWbsPlcyV4/CiiRegAgency")
    @WebResult(name = "CiiRegAgencyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegAgency", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegAgency")
    @ResponseWrapper(localName = "CiiRegAgencyResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegAgencyResponse")
    public WbsV4AgncRes ciiRegAgency(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4AgncReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4BranchRes
     */
    @WebMethod(operationName = "CiiRegBranch", action = "http://tempuri.org/IWbsPlcyV4/CiiRegBranch")
    @WebResult(name = "CiiRegBranchResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegBranch", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegBranch")
    @ResponseWrapper(localName = "CiiRegBranchResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegBranchResponse")
    public WbsV4BranchRes ciiRegBranch(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4BranchReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4BrokerRes
     */
    @WebMethod(operationName = "CiiRegBroker", action = "http://tempuri.org/IWbsPlcyV4/CiiRegBroker")
    @WebResult(name = "CiiRegBrokerResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegBroker", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegBroker")
    @ResponseWrapper(localName = "CiiRegBrokerResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegBrokerResponse")
    public WbsV4BrokerRes ciiRegBroker(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4BrokerReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4CompaniesFildDetailRes
     */
    @WebMethod(operationName = "CiiRegCompaniesFildDetail", action = "http://tempuri.org/IWbsPlcyV4/CiiRegCompaniesFildDetail")
    @WebResult(name = "CiiRegCompaniesFildDetailResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegCompaniesFildDetail", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegCompaniesFildDetail")
    @ResponseWrapper(localName = "CiiRegCompaniesFildDetailResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegCompaniesFildDetailResponse")
    public WbsV4CompaniesFildDetailRes ciiRegCompaniesFildDetail(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4CompaniesFildDetailReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4CurrencyRes
     */
    @WebMethod(operationName = "CiiRegCurrency", action = "http://tempuri.org/IWbsPlcyV4/CiiRegCurrency")
    @WebResult(name = "CiiRegCurrencyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegCurrency", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegCurrency")
    @ResponseWrapper(localName = "CiiRegCurrencyResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegCurrencyResponse")
    public WbsV4CurrencyRes ciiRegCurrency(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4CurrencyReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4IntroRes
     */
    @WebMethod(operationName = "CiiRegIntro", action = "http://tempuri.org/IWbsPlcyV4/CiiRegIntro")
    @WebResult(name = "CiiRegIntroResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegIntro", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegIntro")
    @ResponseWrapper(localName = "CiiRegIntroResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegIntroResponse")
    public WbsV4IntroRes ciiRegIntro(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4IntroReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4PersonTypeRes
     */
    @WebMethod(operationName = "CiiRegPersonType", action = "http://tempuri.org/IWbsPlcyV4/CiiRegPersonType")
    @WebResult(name = "CiiRegPersonTypeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegPersonType", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegPersonType")
    @ResponseWrapper(localName = "CiiRegPersonTypeResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegPersonTypeResponse")
    public WbsV4PersonTypeRes ciiRegPersonType(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4PersonTypeReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4PlcyRes
     */
    @WebMethod(operationName = "CiiRegChkPlcy", action = "http://tempuri.org/IWbsPlcyV4/CiiRegChkPlcy")
    @WebResult(name = "CiiRegChkPlcyResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegChkPlcy", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegChkPlcy")
    @ResponseWrapper(localName = "CiiRegChkPlcyResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegChkPlcyResponse")
    public WbsV4PlcyRes ciiRegChkPlcy(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4PlcyReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param passWrod
     * @param req
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4EdrsRes
     */
    @WebMethod(operationName = "CiiRegEdrs", action = "http://tempuri.org/IWbsPlcyV4/CiiRegEdrs")
    @WebResult(name = "CiiRegEdrsResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegEdrs", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegEdrs")
    @ResponseWrapper(localName = "CiiRegEdrsResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegEdrsResponse")
    public WbsV4EdrsRes ciiRegEdrs(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        WbsV4EdrsReq req,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param passWrod
     * @param req
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4DocLosRes
     */
    @WebMethod(operationName = "CiiRegDocLos", action = "http://tempuri.org/IWbsPlcyV4/CiiRegDocLos")
    @WebResult(name = "CiiRegDocLosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegDocLos", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegDocLos")
    @ResponseWrapper(localName = "CiiRegDocLosResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegDocLosResponse")
    public WbsV4DocLosRes ciiRegDocLos(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        WbsV4DocLosReq req,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param passWrod
     * @param req
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.UpdWbsV4DocLosRes
     */
    @WebMethod(operationName = "CiiUpdDocLos", action = "http://tempuri.org/IWbsPlcyV4/CiiUpdDocLos")
    @WebResult(name = "CiiUpdDocLosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiUpdDocLos", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiUpdDocLos")
    @ResponseWrapper(localName = "CiiUpdDocLosResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiUpdDocLosResponse")
    public UpdWbsV4DocLosRes ciiUpdDocLos(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        UpdWbsV4DocLosReq req,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param losReq
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4LosRes
     */
    @WebMethod(operationName = "CiiRegLos", action = "http://tempuri.org/IWbsPlcyV4/CiiRegLos")
    @WebResult(name = "CiiRegLosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegLos", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegLos")
    @ResponseWrapper(localName = "CiiRegLosResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegLosResponse")
    public WbsV4LosRes ciiRegLos(
        @WebParam(name = "losReq", targetNamespace = "http://tempuri.org/")
        WbsV4LosReq losReq,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4PlcyCvrRes
     */
    @WebMethod(operationName = "CiiRegPlcyCvr", action = "http://tempuri.org/IWbsPlcyV4/CiiRegPlcyCvr")
    @WebResult(name = "CiiRegPlcyCvrResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegPlcyCvr", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegPlcyCvr")
    @ResponseWrapper(localName = "CiiRegPlcyCvrResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegPlcyCvrResponse")
    public WbsV4PlcyCvrRes ciiRegPlcyCvr(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4PlcyCvrReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param pr
     * @param passWrod
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4PlcyMthRes
     */
    @WebMethod(operationName = "CiiRegPlcyMth", action = "http://tempuri.org/IWbsPlcyV4/CiiRegPlcyMth")
    @WebResult(name = "CiiRegPlcyMthResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "CiiRegPlcyMth", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegPlcyMth")
    @ResponseWrapper(localName = "CiiRegPlcyMthResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.CiiRegPlcyMthResponse")
    public WbsV4PlcyMthRes ciiRegPlcyMth(
        @WebParam(name = "Pr", targetNamespace = "http://tempuri.org/")
        WbsV4PlcyMthReq pr,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param passWrod
     * @param req
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4PlcyLifeBaseRes
     */
    @WebMethod(operationName = "RegPlcyLifeBase", action = "http://tempuri.org/IWbsPlcyV4/RegPlcyLifeBase")
    @WebResult(name = "RegPlcyLifeBaseResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RegPlcyLifeBase", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.RegPlcyLifeBase")
    @ResponseWrapper(localName = "RegPlcyLifeBaseResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.RegPlcyLifeBaseResponse")
    public WbsV4PlcyLifeBaseRes regPlcyLifeBase(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        WbsV4PlcyLifeBaseReq req,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param passWrod
     * @param req
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4PlcyLifeRes
     */
    @WebMethod(operationName = "RegPlcyLife", action = "http://tempuri.org/IWbsPlcyV4/RegPlcyLife")
    @WebResult(name = "RegPlcyLifeResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RegPlcyLife", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.RegPlcyLife")
    @ResponseWrapper(localName = "RegPlcyLifeResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.RegPlcyLifeResponse")
    public WbsV4PlcyLifeRes regPlcyLife(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        WbsV4PlcyLifeReq req,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

    /**
     * 
     * @param passWrod
     * @param req
     * @param username
     * @return
     *     returns ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.WbsV4LifeLosRes
     */
    @WebMethod(operationName = "RegLifeLos", action = "http://tempuri.org/IWbsPlcyV4/RegLifeLos")
    @WebResult(name = "RegLifeLosResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RegLifeLos", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.RegLifeLos")
    @ResponseWrapper(localName = "RegLifeLosResponse", targetNamespace = "http://tempuri.org/", className = "ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi.RegLifeLosResponse")
    public WbsV4LifeLosRes regLifeLos(
        @WebParam(name = "req", targetNamespace = "http://tempuri.org/")
        WbsV4LifeLosReq req,
        @WebParam(name = "Username", targetNamespace = "http://tempuri.org/")
        String username,
        @WebParam(name = "PassWrod", targetNamespace = "http://tempuri.org/")
        String passWrod);

}
