
package ir.parsianinsurance.he.interfaces.webservice.client.bimemarkazi;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WbsPlcyV4", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://reinsure.centinsur.ir/WbsPlcyV4?wsdl")
public class WbsPlcyV4
    extends Service
{

    private final static URL WBSPLCYV4_WSDL_LOCATION;
    private final static WebServiceException WBSPLCYV4_EXCEPTION;
    private final static QName WBSPLCYV4_QNAME = new QName("http://tempuri.org/", "WbsPlcyV4");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://reinsure.centinsur.ir/WbsPlcyV4?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WBSPLCYV4_WSDL_LOCATION = url;
        WBSPLCYV4_EXCEPTION = e;
    }

    public WbsPlcyV4() {
        super(__getWsdlLocation(), WBSPLCYV4_QNAME);
    }

    public WbsPlcyV4(WebServiceFeature... features) {
        super(__getWsdlLocation(), WBSPLCYV4_QNAME, features);
    }

    public WbsPlcyV4(URL wsdlLocation) {
        super(wsdlLocation, WBSPLCYV4_QNAME);
    }

    public WbsPlcyV4(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WBSPLCYV4_QNAME, features);
    }

    public WbsPlcyV4(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WbsPlcyV4(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns IWbsPlcyV4
     */
    @WebEndpoint(name = "myBasicHttpBinding_IWbsPlcyV4")
    public IWbsPlcyV4 getMyBasicHttpBindingIWbsPlcyV4() {
        return super.getPort(new QName("http://tempuri.org/", "myBasicHttpBinding_IWbsPlcyV4"), IWbsPlcyV4.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IWbsPlcyV4
     */
    @WebEndpoint(name = "myBasicHttpBinding_IWbsPlcyV4")
    public IWbsPlcyV4 getMyBasicHttpBindingIWbsPlcyV4(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "myBasicHttpBinding_IWbsPlcyV4"), IWbsPlcyV4.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WBSPLCYV4_EXCEPTION!= null) {
            throw WBSPLCYV4_EXCEPTION;
        }
        return WBSPLCYV4_WSDL_LOCATION;
    }

}
