package ir.parsianinsurance.he.domain.model.enums;

/**
 * Created by 8119 on 6/20/2017.
 */
public enum ElateHadese {

    EMPTY,
    PARTSHODAN,
    MAHDODIATE_HAREKATI_AZA,
    NEZA_DARGIRI,
    ASIBDIDGI_AZA,
    ESABATE_JESM_SAKHT,
    BORIDEGI_VA_PAREGI_TANDOONHA,
    BORIDEGI_VA_GHATE_AZA,
    TASADOF,
    TASADOF_RANANDEGI,
    SOOKHTEGI_AZA,
    SHEKASTEGI_VA_KHORDSHODEGI_AZA,
    SOGHOOT_AZ_ERTEFA,
    SOGHOOT_DAR_SATHE_HAMTARAZ,
    GHATL,
    GHARARGEREFTAN_AZA_ZIRE_DASTGAH;
}
